### ISSUE TITLE
Broken when switch is docked

### ISSUE THREAD

**Issue by Armi-Heavy** [WerWolv/ovl-sysmodules#21]
When start ovl-sysmodules and the switch is docked they broken but works fine when switch is on Handheld Mode

Please fix Docked mode, thx.

FW: 16.0.0
CFW: AMS 1.5.1
Tesla-Menu: ovl menu 1.2.1-97b9677

**Comment by WerWolv** [comment]
Make sure the Overscan setting is set to 100%.

**Comment by Armi-Heavy** [comment]
the overscan is already at 100%.

PD: 
* If I use the ovlmenu (edited) from https://github.com/proferabg/EdiZon-Overlay/releases
* And this ovl-sysmodules https://github.com/WerWolv/ovl-sysmodules/issues/19#issuecomment-1453040300

Work Fine, I don´t know what fail in the code
