### ISSUE TITLE
Crash when going back to Testla menu from Sysmodules, in portable mode 

### ISSUE THREAD

**Issue by andrea-ap** [WerWolv/ovl-sysmodules#25]
![1682251384864](https://user-images.githubusercontent.com/63066393/233838682-b3a72ce6-1f2d-40fd-9eab-61105902f29c.jpg)

**Comment by crunchysoft** [comment]
I am getting this same crash/error when attempting to open the sysmodules overlay (1.2.2-9b114b3) from Tesla menu (1.0.6).
I went ahead and uninstalled themes, just in case that was part of the problem, but not change there.
Also made sure I have all of the latest related releases for the switch too.

**Comment by JonJaded** [comment]
Yup having the same issue too.
