### ISSUE TITLE
Sysmodules don't actually toggle

### ISSUE THREAD

**Issue by MultiKoopa** [WerWolv/ovl-sysmodules#26]
I'm on the latest Tesla and Tesla Overlay, latest Sysmodules overlay, Atmosphere 1.5.3, firmware 16.0.2. Pressing A to toggle doesn't actually toggle anything for any of my sysmodules.

**Comment by crunchysoft** [comment]
I'm on latest Tesla/Tesla Overlay/Sysmodules/AMS and 16.0.1 firmware and it crashes my Switch when I attempt to activate Sysmodules from the Tesla Overlay menu.

**Comment by MultiKoopa** [comment]
I think I figured out the toggling.
