### ISSUE TITLE
Does not display sysmodules on ReiNX

### ISSUE THREAD

**Issue by KilimIG** [WerWolv/ovl-sysmodules#4]
When trying to use this with tesla on the latest ReiNX (3.0) it returns that there are 'No sysmodules found!'

is this due to the overlay only scanning for the contents folder under /atmosphere/? ReiNX also uses /contents/ now as well

**Comment by WerWolv** [comment]
Great. Now this shit starts again...

I design my things with Atmosphere and only Atmosphere in mind. If it works anywhere else then great but if not then 🤷 . If the ReiNX people feel like forking 50 different projects again to make them work with their stuff properly, they are allowed. I'm not the one doing it though.

**Comment by KilimIG** [comment]
literally a directory issue bro but whatever
