### ISSUE TITLE
Sysmodules are found but can't be toggled.

### ISSUE THREAD

**Issue by greensad** [WerWolv/ovl-sysmodules#6]
Sysmodules appear correctly, all text and information appears correctly but pressing 'A' does not toggle any sysmodules and toggle auto start does nothing. Other overlays seem to be working as normal. Was working beautifully before updating atmosphere/firmware/overlays.

Latest Tesla Version
ovl-sysmodules v1.2.1
Firmware version 10.0.2 Atmosphere 12 (Emunand)

Edit I was able to solve by uninstalling and reinstalling all sysmodules specifically via the HBshop2, doing so manually had no effect strangely, regardless closing the issue.

**Comment by HookedBehemoth** [comment]
small oversight in the code: autostart can't be enabled if the `flags` folder doesn't exist

**Comment by greensad** [comment]
That could have done it, but just to clarify no sysmodules could be toggled on at all, let alone set to autostart.
